version: '3.9'

networks:
  data-network:
    driver: bridge

volumes:
  mysql_data: {} 
  postgres_data: {}

services:
  mysql:
    image: mysql:8.0
    networks:
      - data-network
    expose:
      - $MYSQL_DOCKER_PORT
    env_file: ./.env
    restart: always
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init1.sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE

  postgres:  
    image: postgres:16-alpine3.18
    networks:
      - data-network
    expose:
      - $POSTGRES_DOCKER_PORT
    env_file: ./.env
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:  
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init2.sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE