version: '3.9'

networks:
  app-network:
    driver: bridge

volumes:
  db_mysql: {}

services:
  db:
    image: mysql:8.0
    networks:
      - app-network
    expose:
      - $MYSQL_DOCKER_PORT
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    env_file: ./.env
    restart: always
    volumes:
      - db_mysql:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD