version: '3.9'

networks:
  app-network:
    driver: bridge

volumes:
  db-postgre: {}

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    expose:
      - $POSTGRES_DOCKER_PORT
    env_file: ./.env
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - db-postgre:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE